//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./feed_types');
//HELPER FUNCTIONS AND STRUCTURES

var FeedService_setFeed_args = function(args) {
  this.feed = null;
  if (args) {
    if (args.feed !== undefined) {
      this.feed = args.feed;
    }
  }
};
FeedService_setFeed_args.prototype = {};
FeedService_setFeed_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.feed = new ttypes.Feed();
        this.feed.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FeedService_setFeed_args.prototype.write = function(output) {
  output.writeStructBegin('FeedService_setFeed_args');
  if (this.feed) {
    output.writeFieldBegin('feed', Thrift.Type.STRUCT, 1);
    this.feed.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var FeedService_setFeed_result = function(args) {
};
FeedService_setFeed_result.prototype = {};
FeedService_setFeed_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FeedService_setFeed_result.prototype.write = function(output) {
  output.writeStructBegin('FeedService_setFeed_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var FeedService_getFeedsByUid_args = function(args) {
  this.uid = null;
  if (args) {
    if (args.uid !== undefined) {
      this.uid = args.uid;
    }
  }
};
FeedService_getFeedsByUid_args.prototype = {};
FeedService_getFeedsByUid_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.uid = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FeedService_getFeedsByUid_args.prototype.write = function(output) {
  output.writeStructBegin('FeedService_getFeedsByUid_args');
  if (this.uid) {
    output.writeFieldBegin('uid', Thrift.Type.I32, 1);
    output.writeI32(this.uid);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var FeedService_getFeedsByUid_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
FeedService_getFeedsByUid_result.prototype = {};
FeedService_getFeedsByUid_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.Feed();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FeedService_getFeedsByUid_result.prototype.write = function(output) {
  output.writeStructBegin('FeedService_getFeedsByUid_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var FeedServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
FeedServiceClient.prototype = {};
FeedServiceClient.prototype.setFeed = function(feed, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_setFeed(feed);
};

FeedServiceClient.prototype.send_setFeed = function(feed) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('setFeed', Thrift.MessageType.CALL, this.seqid);
  var args = new FeedService_setFeed_args();
  args.feed = feed;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

FeedServiceClient.prototype.recv_setFeed = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new FeedService_setFeed_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
FeedServiceClient.prototype.getFeedsByUid = function(uid, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getFeedsByUid(uid);
};

FeedServiceClient.prototype.send_getFeedsByUid = function(uid) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getFeedsByUid', Thrift.MessageType.CALL, this.seqid);
  var args = new FeedService_getFeedsByUid_args();
  args.uid = uid;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

FeedServiceClient.prototype.recv_getFeedsByUid = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new FeedService_getFeedsByUid_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getFeedsByUid failed: unknown result');
};
var FeedServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
FeedServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

FeedServiceProcessor.prototype.process_setFeed = function(seqid, input, output) {
  var args = new FeedService_setFeed_args();
  args.read(input);
  input.readMessageEnd();
  var result = new FeedService_setFeed_result();
  this._handler.setFeed(args.feed, function (success) {
    result.success = success;
    output.writeMessageBegin("setFeed", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

FeedServiceProcessor.prototype.process_getFeedsByUid = function(seqid, input, output) {
  var args = new FeedService_getFeedsByUid_args();
  args.read(input);
  input.readMessageEnd();
  var result = new FeedService_getFeedsByUid_result();
  this._handler.getFeedsByUid(args.uid, function (success) {
    result.success = success;
    output.writeMessageBegin("getFeedsByUid", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

